DATABASE="dev_gym_api"
DB_USER="dev_gym_api"
createdb $DATABASE
psql -d $DATABASE -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"'
psql -d $DATABASE -c "CREATE ROLE $DB_USER"
psql -d $DATABASE -c "GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO $DB_USER"
